(() => {
  const app = document.querySelector('#app');
  const route = window.__LP_ROUTE__ || '/';
  const icon = (name) => `<span aria-hidden="true">${({home:'⌂',system:'▣',docker:'◫',files:'▤',security:'◇',ssh:'⌁',settings:'⚙',trash:'⌫',plus:'＋'}[name] || '•')}</span>`;
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nav = [
    ['/', '概览', 'home'], ['/system', '系统', 'system'], ['/docker', 'Docker', 'docker'],
    ['/files', '文件', 'files'], ['/security', '安全', 'security'], ['/ssh', 'SSH', 'ssh'], ['/settings', '设置', 'settings']
  ];
  const pageHeader = (title, desc, actions='') => `<header class="page-header"><div class="page-header__main"><div class="page-header__copy"><h1>${title}</h1><p>${desc}</p></div></div><div class="page-header__actions">${actions}</div></header>`;
  function shell(content) {
    return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark" aria-hidden="true"></div><div><strong>LukePanel</strong><span>v2.0.0</span></div></div><nav class="sidebar-nav">${nav.map(n=>`<a class="${route===n[0]?'active':''}" href="#">${icon(n[2])}<span>${n[1]}</span></a>`).join('')}</nav><div class="sidebar-footer"><div class="sidebar-user-card"><div class="user-avatar">L</div><div><strong>Lukeadmin</strong><small>管理员</small></div></div><button class="icon-text-button">退出登录</button></div></aside><main class="main-content"><div class="page-wrap">${content}</div></main><nav class="mobile-nav">${[['/','概览','home'],['/docker','Docker','docker'],['/files','文件','files'],['/security','安全','security'],['/settings','设置','settings']].map(n=>`<a class="${route===n[0]?'active':''}" href="#">${icon(n[2])}<span>${n[1]}</span></a>`).join('')}</nav></div>`;
  }
  function dashboard() {
    const cards = [['CPU 负载','0.18','2 核'],['内存','37%','768 MB / 2 GB'],['Swap','13%','128 MB / 1 GB'],['系统盘','24%','12 GB / 50 GB']];
    return shell(`${pageHeader('系统概览','实时查看服务器资源、服务与关键状态。','<button class="secondary-button">立即刷新</button>')}<div class="live-status-strip"><div><i class="live-dot"></i><strong>实时数据已连接</strong></div><time>刚刚更新</time></div><section class="overview-kpi-grid">${cards.map((x,i)=>`<article class="surface overview-stat-card"><div class="overview-stat-icon">${i+1}</div><div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div></article>`).join('')}</section><section class="overview-main-grid"><article class="content-panel"><div class="panel-heading"><div><h2>资源使用</h2><p>系统主要资源占用</p></div><span class="state-pill success">正常</span></div>${['CPU','内存','Swap','系统盘'].map((n,i)=>`<div class="resource-meter-row"><div><strong>${n}</strong><span>${[18,37,13,24][i]}%</span></div><div class="resource-meter-track"><i style="width:${[18,37,13,24][i]}%"></i></div><small>当前使用处于安全范围</small></div>`).join('')}</article><article class="content-panel"><div class="panel-heading"><div><h2>服务状态</h2><p>关键组件</p></div></div><div class="info-list"><div><dt>Web API</dt><dd><span class="state-pill success">在线</span></dd></div><div><dt>Root Agent</dt><dd><span class="state-pill success">在线</span></dd></div><div><dt>Docker</dt><dd><span class="state-pill success">运行中</span></dd></div></div></article></section><section class="module-grid" style="margin-top:16px">${['系统管理','Docker 管理','文件管理','安全中心','SSH 管理','日志审计'].map((n,i)=>`<a class="module-card"><div class="module-icon">${i+1}</div><div><strong>${n}</strong><p>真实功能入口与状态摘要。</p></div><span>›</span></a>`).join('')}</section>`);
  }
  function security() {
    const rules = [
      {n:1,to:'22/tcp',action:'ALLOW IN',from:'Anywhere',v:'IPv4'},
      {n:2,to:'80,443/tcp',action:'ALLOW IN',from:'10.0.0.0/8',v:'IPv4'},
      {n:3,to:'853',action:'DENY IN',from:'Anywhere (v6)',v:'IPv6'}
    ];
    return shell(`${pageHeader('安全中心','统一管理登录保护、访问控制、Fail2ban 与 UFW。','<button class="secondary-button">刷新状态</button>')}<section class="security-overview surface"><div class="security-score" style="--score:92"><strong>92</strong><span>/100</span></div><div><h2>整体防护良好</h2><p>Agent 在线，UFW 已启用，当前共 3 条编号规则。</p></div></section><section class="security-grid"><article class="security-feature"><div class="panel-heading"><div><h2>UFW 防火墙</h2><p>默认拒绝入站，允许出站</p></div><span class="state-pill success">已启用</span></div><form id="ufw-rule-form" class="firewall-rule-form"><label class="firewall-field"><span>动作</span><select name="action"><option>允许</option><option>拒绝</option><option>拒绝并响应</option><option>连接限速</option></select></label><label class="firewall-field"><span>方向</span><select name="direction"><option>入站</option><option>出站</option></select></label><label class="firewall-field"><span>协议</span><select name="protocol"><option>TCP</option><option>UDP</option><option>全部协议</option></select></label><label class="firewall-field"><span>端口或范围</span><input name="port" inputmode="numeric" placeholder="443 或 1000:2000"></label><label class="firewall-field"><span>来源 IP / CIDR</span><input name="source" placeholder="留空表示任意来源"></label><label class="firewall-field"><span>备注</span><input name="comment" placeholder="例如 HTTPS"></label><button class="primary-button firewall-rule-submit">${icon('plus')}<span>添加规则</span></button></form><div class="firewall-rule-list">${rules.map(r=>`<article class="firewall-rule-card"><div class="firewall-rule-number">#${r.n}</div><div class="firewall-rule-content"><div class="firewall-rule-heading"><strong>${esc(r.to)}</strong><span class="state-pill ${r.action.includes('ALLOW')?'success':'warning'}">${r.action}</span></div><p>来源：${esc(r.from)}</p><small>${r.v} · 编号规则</small></div><button class="danger-button compact firewall-rule-delete" data-ufw-delete="${r.n}">${icon('trash')}<span>删除</span></button></article>`).join('')}</div></article><article class="security-feature"><div class="panel-heading"><div><h2>登录保护</h2><p>账户与二次验证</p></div></div><div class="setting-row"><div class="setting-icon">2F</div><div><strong>TOTP</strong><p class="muted">已启用</p></div><span class="state-pill success">安全</span></div><div class="setting-row"><div class="setting-icon">PK</div><div><strong>Passkey</strong><p class="muted">2 个凭据</p></div><button class="secondary-button compact">管理</button></div><div class="setting-row"><div class="setting-icon">IP</div><div><strong>IP 白名单</strong><p class="muted">未限制来源</p></div><button class="secondary-button compact">配置</button></div></article></section>`);
  }
  function dockerPage() {
    const names = ['nginx-proxy-manager','AdGuardHome','mosdns','uptime-kuma'];
    return shell(`${pageHeader('Docker 管理','容器、镜像、网络、存储卷与 Compose。','<button class="primary-button">创建容器</button><button class="secondary-button">刷新</button>')}<div class="tab-bar surface"><button class="active">容器</button><button>镜像</button><button>网络</button><button>存储卷</button><button>Compose</button></div><section class="container-grid">${names.map((n,i)=>`<article class="container-card"><div class="container-card__top"><div class="container-icon">D</div><div><strong>${n}</strong><span class="state-pill ${i===3?'warning':'success'}">${i===3?'已停止':'运行中'}</span></div></div><p>linux/amd64 · bridge 网络</p><div class="container-live-stats"><span>CPU ${(i+1)*0.7}%</span><span>内存 ${64+i*43} MB</span><span>网络 ${i+1}.2 MB</span></div><div class="resource-actions"><button class="secondary-button compact">日志</button><button class="secondary-button compact">编辑</button><button class="danger-button compact">删除</button></div></article>`).join('')}</section>`);
  }
  function filesPage() {
    const files = [['etc','文件夹','--'],['opt','文件夹','--'],['home','文件夹','--'],['README.md','Markdown','8 KB'],['config.yaml','YAML','4 KB'],['backup.tar.gz','压缩包','126 MB']];
    return shell(`${pageHeader('文件管理','浏览、上传、编辑、压缩与回收站。','<button class="primary-button">上传</button><button class="secondary-button">新建</button>')}<div class="file-toolbar surface"><button class="secondary-button compact">‹</button><nav class="file-breadcrumb"><button>/</button><span>›</span><button>opt</button><span>›</span><button>lukepanel</button></nav><button class="secondary-button compact">复制路径</button></div><section class="surface file-entry-list">${files.map((f,i)=>`<div class="file-row"><button class="file-open"><span class="file-icon">${i<3?'▤':'·'}</span><span class="file-main"><strong>${f[0]}</strong><span>${f[1]}</span></span><code>${f[2]}</code></button><button class="file-more">⋯</button></div>`).join('')}</section><section class="shortcut-panel surface"><div class="panel-heading"><div><h2>常用位置</h2><p>快速访问服务器目录</p></div></div><div class="shortcut-grid"><button class="shortcut-item">/etc</button><button class="shortcut-item">/opt</button><button class="shortcut-item">/var/log</button><button class="shortcut-item">/root</button></div></section>`);
  }
  function settingsPage() {
    return shell(`${pageHeader('面板设置','账户、外观、刷新、安全和备份。','<button class="primary-button">保存设置</button>')}<section class="account-grid"><article class="account-panel"><div class="panel-heading"><div><h2>账户信息</h2><p>用于登录面板</p></div></div><form><label>用户名<input value="Lukeadmin"></label><label>显示名称<input value="Luke"></label><button class="primary-button">更新账户</button></form></article><article class="password-panel"><div class="panel-heading"><div><h2>修改密码</h2><p>至少 12 位并包含多种字符</p></div></div><form><label>当前密码<input type="password" value="password"></label><label>新密码<input type="password" value="new password"></label><label>确认新密码<input type="password" value="new password"></label><div class="password-strength"><div><span style="width:72%"></span></div><strong>较强</strong></div><button class="primary-button">更新密码</button></form></article></section><section class="settings-list" style="margin-top:16px"><div class="setting-row"><div class="setting-icon">◐</div><div><strong>外观</strong><p class="muted">跟随系统</p></div><select><option>跟随系统</option><option>浅色</option><option>深色</option></select></div><div class="setting-row"><div class="setting-icon">↻</div><div><strong>实时刷新</strong><p class="muted">概览数据刷新间隔</p></div><select><option>5 秒</option></select></div><div class="setting-row"><div class="setting-icon">BK</div><div><strong>自动备份</strong><p class="muted">每天保留 7 份配置备份</p></div><button class="secondary-button">管理备份</button></div></section>`);
  }
  function sshPage() {
    return shell(`${pageHeader('SSH 管理','端口、密码登录、密钥与 Linux 用户。','<button class="secondary-button">刷新状态</button>')}<section class="ssh-overview-grid"><article class="ssh-status-panel" style="padding:16px"><div class="panel-heading"><div><h2>SSH 服务</h2><p>OpenSSH Server</p></div><span class="state-pill success">运行中</span></div><div class="ssh-metrics-grid"><div><span>端口</span><strong>22</strong></div><div><span>密码登录</span><strong>关闭</strong></div><div><span>Root 登录</span><strong>密钥</strong></div><div><span>密钥数量</span><strong>2</strong></div></div></article><article class="ssh-settings-panel" style="padding:16px"><div class="panel-heading"><div><h2>连接设置</h2><p>修改前自动预检</p></div></div><form class="form-grid"><label>SSH 端口<input inputmode="numeric" value="22"></label><label>密码登录<select><option>关闭</option><option>开启</option></select></label><button class="primary-button wide-field">保存并校验</button></form></article></section><section class="ssh-keys-panel" style="padding:16px;margin-top:16px"><div class="panel-heading"><div><h2>授权密钥</h2><p>当前用户 authorized_keys</p></div><button class="primary-button">生成密钥</button></div><div class="key-list"><div class="key-list-row"><span class="key-type-badge">ED25519</span><div><strong>iPhone</strong><p class="muted">SHA256:3g9…zPy</p></div><button class="danger-button compact">删除</button></div><div class="key-list-row"><span class="key-type-badge">RSA</span><div><strong>MacBook</strong><p class="muted">SHA256:9xK…vQe</p></div><button class="danger-button compact">删除</button></div></div></section>`);
  }
  function dialogPage() {
    return shell(`${pageHeader('交互组件测试','验证弹窗、键盘、安全区和长内容滚动。')}<article class="content-panel"><h2>底层页面</h2><p>弹窗打开时页面滚动应锁定，手机端应采用底部抽屉布局。</p></article><div class="modal-backdrop"><section class="modal-card wide"><header><div><strong>编辑 Docker Compose</strong><small>docker-compose.yml</small></div><button aria-label="关闭">×</button></header><div class="modal-body"><div class="form-grid"><label>项目名称<input value="lukepanel-stack"></label><label>工作目录<input value="/opt/stacks/lukepanel"></label></div><label style="display:grid;margin-top:13px">Compose 内容<textarea style="min-height:320px">services:\n  app:\n    image: example/app:latest\n    restart: unless-stopped\n    ports:\n      - 8080:8080</textarea></label></div><footer><button class="secondary-button">取消</button><button class="primary-button">保存并部署</button></footer></section></div>`);
  }
  function loginPage() {
    return `<main class="login-page"><section class="login-card surface"><div class="login-brand"><div class="login-logo"></div><div><strong>LukePanel</strong><span>安全服务器管理面板</span></div></div><h1>登录管理面板</h1><form><label>用户名<input value="Lukeadmin" autocomplete="username"></label><label>密码<div class="password-field"><input type="password" value="password" autocomplete="current-password"><button type="button">显示</button></div></label><div class="form-error">用户名或密码不正确，请重新输入。</div><button class="primary-button wide-button">登录</button></form><div class="login-divider">或</div><button class="secondary-button wide-button">使用 Passkey 登录</button></section></main>`;
  }
  const pages = {'/':dashboard,'/security':security,'/docker':dockerPage,'/files':filesPage,'/settings':settingsPage,'/ssh':sshPage,'/dialog':dialogPage,'/login':loginPage};
  app.innerHTML = (pages[route] || dashboard)();
})();
