import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { api, errorText } from '../lib/api';
import { asArray, formatDate } from '../lib/format';
import { useApiData } from '../lib/useApiData';
import { useDialog } from '../components/Dialog';
import { useToast } from '../components/Toast';
import { Icon } from '../components/Icon';
import { Button, Card, CodeBlock, EmptyState, ErrorState, Loading, PageHeader, ResourceRow, SearchBox, Status, Tabs } from '../components/UI';
import type { PageNavProps } from './SystemPages';

type Tab='audit'|'system';

export function LogsPage({back}:PageNavProps){
 const [tab,setTab]=useState<Tab>('audit');const [query,setQuery]=useState('');const [filters,setFilters]=useState({user:'',ip:'',action:'',result:'',from:'',to:''});const params=new URLSearchParams({q:query,...filters,limit:'200',offset:'0'});const audit=useApiData<Record<string,any>>(tab==='audit'?`/api/v1/audit?${params}`:null,{deps:[tab,query,filters.user,filters.ip,filters.action,filters.result,filters.from,filters.to]});const [unit,setUnit]=useState('');const [priority,setPriority]=useState('');const system=useApiData<Record<string,any>>(tab==='system'?`/api/v1/logs/system?unit=${encodeURIComponent(unit)}&priority=${encodeURIComponent(priority)}&lines=500`:null,{deps:[tab,unit,priority]});const dialog=useDialog();const toast=useToast();
 const events=asArray<Record<string,any>>(audit.data?.events??audit.data?.items);const logs=String(system.data?.logs??system.data?.output??'');
 async function copy(value:string){try{await navigator.clipboard.writeText(value);toast('已复制');}catch{await dialog.alert('复制失败，请长按文本手动复制');}}
 return <div className="page"><PageHeader title="日志审计" description="审计记录和 systemd Journal 均来自真实后端" back={back} actions={<Button compact onClick={()=>tab==='audit'?audit.reload():system.reload()}><Icon name="refresh" size={17}/>刷新</Button>}/><Tabs value={tab} onChange={setTab} items={[{value:'audit',label:'操作审计',count:Number(audit.data?.total??events.length)},{value:'system',label:'系统日志'}]}/>{tab==='audit'?<><SearchBox value={query} onChange={setQuery} placeholder="搜索动作、目标或详情"/><Card><form className="filter-grid" onSubmit={e=>e.preventDefault()}><label>用户<input value={filters.user} onChange={e=>setFilters({...filters,user:e.target.value})}/></label><label>IP<input value={filters.ip} onChange={e=>setFilters({...filters,ip:e.target.value})}/></label><label>动作<input value={filters.action} onChange={e=>setFilters({...filters,action:e.target.value})}/></label><label>结果<select value={filters.result} onChange={e=>setFilters({...filters,result:e.target.value})}><option value="">全部</option><option value="success">成功</option><option value="failed">失败</option></select></label><label>开始<input type="datetime-local" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>结束<input type="datetime-local" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label></form></Card>{audit.loading&&!audit.data?<Loading/>:audit.error&&!audit.data?<ErrorState message={audit.error} retry={audit.reload}/>:events.length?<Card className="resource-list audit-list">{events.map((item,index)=>{const text=JSON.stringify(item,null,2);return <ResourceRow key={`${item.id||item.time||index}`} title={String(item.action||'unknown')} subtitle={`${item.user||'-'} · ${item.ip||'-'} · ${item.target||'-'}`} meta={`${formatDate(item.time||item.created_at)}${item.detail?` · ${item.detail}`:''}`} status={<Status value={item.result}/>} actions={<Button compact onClick={()=>copy(text)}><Icon name="copy" size={16}/>复制</Button>}/>;})}</Card>:<Card><EmptyState title="没有匹配的审计记录"/></Card>}</>:<><Card><form className="inline-form" onSubmit={e=>{e.preventDefault();system.reload();}}><label className="grow">systemd 单元<input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="留空查看系统日志，或输入 ssh.service"/></label><label>优先级<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">全部</option><option value="0..3">错误及以上</option><option value="0..4">警告及以上</option><option value="0..6">信息及以上</option></select></label><Button type="submit">读取</Button></form></Card>{system.loading&&!system.data?<Loading/>:system.error&&!system.data?<ErrorState message={system.error} retry={system.reload}/>:<Card><CodeBlock value={logs||'暂无日志'} copy={copy}/></Card>}</>}</div>;
}
