package server

import (
	"bytes"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

var releaseVersionPattern = regexp.MustCompile(`^v[0-9][A-Za-z0-9._-]*$`)

func repositoryVersion(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "VERSION"))
	if err != nil {
		t.Fatal(err)
	}
	version := strings.TrimSpace(string(raw))
	if !releaseVersionPattern.MatchString(version) {
		t.Fatalf("invalid VERSION value %q", version)
	}
	return version
}

func TestAgentServiceFilesPreserveAPTPrivilegeTransitions(t *testing.T) {
	root := filepath.Join("..", "..")
	paths := []string{
		filepath.Join(root, "install.sh"),
		filepath.Join(root, "packaging", "systemd", "lukepanel-agent.service"),
	}
	required := []string{"User=root", "NoNewPrivileges=false", "CapabilityBoundingSet=~", "RestrictSUIDSGID=false", "ProtectKernelModules=false"}
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		for _, directive := range required {
			if !strings.Contains(string(raw), directive) {
				t.Fatalf("%s is missing required Agent directive %q", path, directive)
			}
		}
	}
}

func TestReadmeIsPublicProjectDocumentation(t *testing.T) {
	version := repositoryVersion(t)
	raw, err := os.ReadFile(filepath.Join("..", "..", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	readme := string(raw)
	for _, required := range []string{"## 主要特点", "## 支持范围", "## 安装", "## 安全模型", "## 本地开发", "当前版本：<code>" + version + "</code>", "React 18", "TypeScript", "离线构建"} {
		if !strings.Contains(readme, required) {
			t.Fatalf("README is missing public documentation section %q", required)
		}
	}
	for _, forbidden := range []string{"obliviatedig.top", "只适合我", "我的服务器", "按我的环境"} {
		if strings.Contains(strings.ToLower(readme), strings.ToLower(forbidden)) {
			t.Fatalf("README still contains user-specific wording %q", forbidden)
		}
	}
}

func TestStableReleaseMetadataIsConsistent(t *testing.T) {
	root := filepath.Join("..", "..")
	version := repositoryVersion(t)
	plainVersion := strings.TrimPrefix(version, "v")
	checks := map[string][]string{
		filepath.Join(root, "README.md"):    {"当前版本：<code>" + version + "</code>", "## " + version + " React 全量重构"},
		filepath.Join(root, "SECURITY.md"):  {"LukePanel " + version},
		filepath.Join(root, "CHANGELOG.md"): {"## " + version + " - "},
	}
	for path, required := range checks {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		for _, marker := range required {
			if !strings.Contains(string(raw), marker) {
				t.Fatalf("%s is missing stable release marker %q", path, marker)
			}
		}
	}
	packageRaw, err := os.ReadFile(filepath.Join(root, "frontend", "package.json"))
	if err != nil {
		t.Fatal(err)
	}
	var pkg struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(packageRaw, &pkg); err != nil {
		t.Fatal(err)
	}
	if pkg.Version != plainVersion {
		t.Fatalf("frontend package version %q does not match VERSION %q", pkg.Version, version)
	}
}

func TestReleaseFrontendHasNoLegacyRuntimeOrDebugStatements(t *testing.T) {
	root := filepath.Join("..", "..")
	if _, err := os.Stat(filepath.Join(root, "web", "app.js")); !os.IsNotExist(err) {
		t.Fatal("legacy web/app.js is still present; production web must be generated by the React build")
	}
	for _, path := range []string{
		filepath.Join(root, "frontend", "src"),
		filepath.Join(root, "frontend", "index.html"),
	} {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		if !info.IsDir() {
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			if strings.Contains(string(raw), "debugger;") || strings.Contains(string(raw), "console.log(") {
				t.Fatalf("%s contains debug residue", path)
			}
			continue
		}
		err = filepath.WalkDir(path, func(current string, entry os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			raw, readErr := os.ReadFile(current)
			if readErr != nil {
				return readErr
			}
			content := string(raw)
			if strings.Contains(content, "debugger;") || strings.Contains(content, "console.log(") {
				t.Fatalf("%s contains debug residue", current)
			}
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
}

func TestEmbeddedFrontendMatchesSource(t *testing.T) {
	root := filepath.Join("..", "..")
	sourceRoot := filepath.Join(root, "web")
	var sourceFiles []string
	if err := filepath.WalkDir(sourceRoot, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(sourceRoot, path)
		if err != nil {
			return err
		}
		sourceFiles = append(sourceFiles, filepath.ToSlash(rel))
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	var embeddedFiles []string
	if err := fs.WalkDir(webAssets, "webdist", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		embeddedFiles = append(embeddedFiles, strings.TrimPrefix(filepath.ToSlash(path), "webdist/"))
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	sort.Strings(sourceFiles)
	sort.Strings(embeddedFiles)
	if strings.Join(sourceFiles, "\n") != strings.Join(embeddedFiles, "\n") {
		t.Fatalf("embedded file set differs from web; run make frontend-sync\nsource=%v\nembedded=%v", sourceFiles, embeddedFiles)
	}
	for _, name := range sourceFiles {
		source, err := os.ReadFile(filepath.Join(sourceRoot, filepath.FromSlash(name)))
		if err != nil {
			t.Fatal(err)
		}
		embedded, err := webAssets.ReadFile("webdist/" + name)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(source, embedded) {
			t.Fatalf("embedded frontend is stale for %s; run make frontend-sync", name)
		}
	}
}
